AWSTemplateFormatVersion: '2010-09-09'

Description: Stratus External YAML Sample

Resources:
  SampleParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: Hello world!
