---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang:1.11
    commands:
      - go get -u github.com/mgechev/revive
      - revive -config .revive.toml -exclude vendor/... -formatter friendly ./...
      - go test -cover -v ./...
      - go vet -all -shadow ./...
    when:
      event:
        exclude:
          - pull_request
          - tag
  - name: publish (static)
    image: plugins/docker
    depends_on:
      - clone
    settings:
      password:
        from_secret: docker-hub.password
      repo: 72636c/stratus
      tags:
        - latest
        - latest-static
      target: final-static
      username:
        from_secret: docker-hub.username
    when:
      branch:
        - master
      event:
        - push
  - name: publish (alpine)
    image: plugins/docker
    depends_on:
      - clone
    settings:
      password:
        from_secret: docker-hub.password
      repo: 72636c/stratus
      tags: latest-alpine
      target: final-alpine
      username:
        from_secret: docker-hub.username
    when:
      branch:
        - master
      event:
        - push

---
kind: signature
hmac: 081718733c3f8a35eaf29de2ffcd04570dce44cca1f41e773f83ca5a5649d77a
