---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang:1.11
    commands:
      - go get -u github.com/mgechev/revive
      - revive -config .revive.toml -exclude vendor/... -formatter friendly ./...
      - go test -cover -v ./...
      - go vet -all -shadow ./...
    when:
      event:
        exclude:
          - pull_request
          - tag

---
kind: signature
hmac: b44888cdd8bb1871fc6789a26bb6c976f7a124789daccefc53108ba016e3e3e2
