---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    depends_on:
      - clone
    settings:
      dry_run: true
      repo: 72636c/stratus
    when:
      event:
        - pull_request
        - push

  - name: test
    image: 72636c/golang:1.12
    commands:
      - revive -config .revive.toml -exclude vendor/... -formatter friendly ./...
      - go test -cover -v ./...
      - go vet ./...
      - go vet -vettool="$(command -v shadow)" ./...
    depends_on:
      - clone
    when:
      event:
        - pull_request
        - push

  - name: push (base)
    image: plugins/docker
    depends_on:
      - clone
    settings:
      password:
        from_secret: docker-hub.password
      repo: 72636c/stratus
      tags: base
      target: final-base
      username:
        from_secret: docker-hub.username
    when:
      branch:
        - master
      event:
        - push

  - name: push (static)
    image: plugins/docker
    depends_on:
      - clone
    settings:
      password:
        from_secret: docker-hub.password
      repo: 72636c/stratus
      tags:
        - latest
        - static
      target: final-static
      username:
        from_secret: docker-hub.username
    when:
      branch:
        - master
      event:
        - push

---
kind: signature
hmac: 8aecfe8b5d4a0f71b318392ec03a78e7fe91d295545b47a28ea2f0ab28f79edc
