---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: 72636c/golang:1.11
    commands:
      - revive -config .revive.toml -exclude vendor/... -formatter friendly ./...
      - go test -cover -v ./...
      - go vet -all -shadow ./...
    when:
      event:
        exclude:
          - pull_request
          - tag

  - name: publish (static)
    image: plugins/docker
    depends_on:
      - clone
    settings:
      password:
        from_secret: docker-hub.password
      repo: 72636c/stratus
      tags:
        - latest
        - latest-static
      target: final-static
      username:
        from_secret: docker-hub.username
    when:
      branch:
        - master
      event:
        - push

  - name: publish (alpine)
    image: plugins/docker
    depends_on:
      - clone
    settings:
      password:
        from_secret: docker-hub.password
      repo: 72636c/stratus
      tags: latest-alpine
      target: final-alpine
      username:
        from_secret: docker-hub.username
    when:
      branch:
        - master
      event:
        - push

---
kind: signature
hmac: 535226e1ae51a447673030b4660642980999ec79175fb9de5360769f35683479
