---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: 72636c/golang:1.12
    commands:
      - revive -config .revive.toml -exclude vendor/... -formatter friendly ./...
      - go test -cover -v ./...
      - go vet ./...
      - go vet -vettool="$(command -v shadow)" ./...
    when:
      branch:
        exclude:
          - master
      event:
        exclude:
          - pull_request
          - tag

  - name: publish (static)
    image: plugins/docker
    depends_on:
      - clone
    settings:
      password:
        from_secret: docker-hub.password
      repo: 72636c/stratus
      tags:
        - latest
        - latest-static
      target: final-static
      username:
        from_secret: docker-hub.username
    when:
      branch:
        - master
      event:
        - push

  - name: publish (busybox)
    image: plugins/docker
    depends_on:
      - clone
    settings:
      password:
        from_secret: docker-hub.password
      repo: 72636c/stratus
      tags: latest-busybox
      target: final-busybox
      username:
        from_secret: docker-hub.username
    when:
      branch:
        - master
      event:
        - push

---
kind: signature
hmac: c62534567f9d79f65082bf6bc179648463d856e95a2ee0e3eb7bb8d41d549b75
