---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang:1.11
    commands:
      - go get -u github.com/mgechev/revive
      - revive -config .revive.toml -exclude vendor/... -formatter friendly ./...
      - go test -cover -v ./...
      - go vet -all -shadow ./...
    when:
      event:
        exclude:
          - pull_request
          - tag
  - name: publish
    image: plugins/docker
    settings:
      password:
        from_secret: docker-hub.password
      repo: 72636c/stratus
      tags: latest
      username:
        from_secret: docker-hub.username
    when:
      # branch:
      #   - master
      event:
        - push

---
kind: signature
hmac: 1962428ba8510c3f24d9cfa158117b1c078aacf76cecbb5222cf5888a3e170e9
