---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    depends_on:
      - clone
    settings:
      dry_run: true
      repo: 72636c/stratus
    when:
      branch:
        exclude:
          - master
      event:
        - push

  - name: test
    image: 72636c/golang:1.12
    commands:
      - revive -config .revive.toml -exclude vendor/... -formatter friendly ./...
      - go test -cover -v ./...
      - go vet ./...
      - go vet -vettool="$(command -v shadow)" ./...
    depends_on:
      - clone
    when:
      branch:
        exclude:
          - master
      event:
        - push

  - name: push (base)
    image: plugins/docker
    depends_on:
      - clone
    settings:
      password:
        from_secret: docker-hub.password
      repo: 72636c/stratus
      tags: base
      target: final-base
      username:
        from_secret: docker-hub.username
    when:
      branch:
        - master
      event:
        - push

  - name: push (static)
    image: plugins/docker
    depends_on:
      - clone
    settings:
      password:
        from_secret: docker-hub.password
      repo: 72636c/stratus
      tags:
        - latest
        - static
      target: final-static
      username:
        from_secret: docker-hub.username
    when:
      branch:
        - master
      event:
        - push

---
kind: signature
hmac: 514108390b23d037b12543b86af13f5039d576843aeab4a29b3519547f0bd4f6
