name: Release

on:
  workflow_run:
    branches:
      - main
    types:
      - completed
    workflows:
      - Validate

permissions: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (base)
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            72636c/stratus:base
          target: final-base

      - name: Build & Push (static)
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            72636c/stratus:latest
            72636c/stratus:static
          target: final-static
